name: CI

on:
  push:
  pull_request:

jobs:
  coding-standards:
    name: Coding standards
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php_version: [8.0, 8.1, 8.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install PHP dependencies (composer install)
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php_version }}
      - name: Easy Coding Standards
        run: composer ecs
      - name: PHPMD
        run: composer phpmd
      - name: PHPStan
        run: composer phpstan
  tests:
    name: Tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php_version: [8.0, 8.1, 8.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install PHP dependencies (composer install)
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php_version }}
      - name: PHPUnit
        run: composer test
